ansible_connection: local
hostname: "raspberrypi-music"

mopidy:
  conf:
    src: "mopidy.conf"
    dest: "{{ user.home }}/.config/mopidy/mopidy.conf"
qbit:
  service:
    src: "service.conf"
    dest: "/etc/systemd/system/qbittorrent.service"
ssh:
  password_auth: true
  root_login: false
  conf:
    dest: "{{ user.home }}/.ssh/"
  auth_keys:
    src: "authorized_keys"
    dest: "{{ user.home }}/.ssh/authorized_keys"
  login_success: "Login Successfull"
user:
    home: "{{ lookup('env','HOME') }}"
    name: "pi"
    password: "$6$ynphz2vBBCTBDY2T$O.IpK7LgeX8uTi4Bq04BNEm1.AvexqSid9IJGjE.e81Z6DH.3nT6HgtB.xlG/02r1IqVh7PKjSH3C6CrFeJKA."