ansible_connection: local
hostname: "raspberrypi-music"
service_dir: "/etc/systemd/system"

user:
    home: "{{ lookup('env','HOME') }}"
    name: "pi"
    password: "$6$ynphz2vBBCTBDY2T$O.IpK7LgeX8uTi4Bq04BNEm1.AvexqSid9IJGjE.e81Z6DH.3nT6HgtB.xlG/02r1IqVh7PKjSH3C6CrFeJKA."