################################################################################
# ANSIBLE configuration file to setup workstation softwares and configurations #
################################################################################

---
- hosts: local
  connection: local
  become: yes
  vars_files:
    - vars.yml

  roles:
    - role: git
    - role: ssh
    - role: qbit
    - role: mopidy