################################################################################
# ANSIBLE configuration file to setup workstation softwares and configurations #
################################################################################

---
- hosts: local
  connection: local
  become: yes
  any_errors_fatal: true # Set to true to abort the entire playbook on failure
  vars_files:
    - group_vars/vars.yml

  roles:
    - role: system
    - role: ssh
    - role: qbt
    - role: mopidy