---
- name: "Install qBittorrent"
  package:
    name: qbittorrent-nox
    state: latest

- name: "Add user {{ qbt.user.name }}"
  user:
    name: "{{ qbt.user.name }}"
    state: present
    groups: "{{ user.name }}"
    # shell: /usr/sbin/nologin
    create_home: yes
    system: yes
    comment: "qBittorrent client user"
    
- name: "Create qBittorrent configuration directory"
  file:
    path: "{{ qbt.conf.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ qbt.user.name }}"
    mode: 0755

- name: "Copy qBittorrent configuration file"
  copy:
    src: "{{ qbt.service.src }}"
    dest: "{{ qbt.service.dest }}"
    owner: "{{ user.name }}"
    group: "{{ qbt.user.name }}"
    mode: 0644
  register: copy_result
  changed_when: copy_result.changed
  failed_when: copy_result.failed
  ignore_errors: true

- name: "State of {{ qbt.service.src }}"
  debug: 
    var: copy_result.state
    verbosity: "0"

- name: "Activate service {{ qbt.service.name }}"
  systemd:
    name: "{{ qbt.service.name }}"
    state: started
    daemon_reload: yes
    enabled: yes
  register: service_status
  changed_when: service_status.changed
  # failed_when: service_status.status.ActiveState != "active"
  ignore_errors: true

- name: "State of service {{ qbt.service.name }}"
  debug: 
    var: service_status.status.ActiveState
    verbosity: "0"