---
- name: "Install SSH Server"
  apt:
    name: openssh-server
    state: latest
    cache_valid_time: 3600

- name: "{{ ssh.password_auth | ternary('Allow','Disallow') }} password authentication"
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication {{ ssh.password_auth | ternary('yes','no') }}"
    state: present

- name: "{{ ssh.root_login | ternary('Allow','Disallow') }} root SSH access"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin {{ ssh.root_login | ternary('yes','no') }}"
    state: present

- name: "Add authorized_keys"
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ item }}"
    state: present
  with_lines: "cat {{ ssh.auth_keys.src }}"
  
- name: "Ensure SSH is started"
  service:
    name: ssh
    state: restarted
    enabled: true
