---
- name: update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Set timezone to EST
  timezone:
   name: America/New_York

- name: Ensure utility present
  package:
    name: sshpass
    state: present

- name: Check for default password
  command: sshpass -p raspberry ssh {{ user.name }}@localhost -o NoHostAuthenticationForLocalhost=yes
  register: try_login
  changed_when: False
  failed_when: False

- name: Warning new password
  debug:
    msg: "Changing default password for user {{ user.name }}"
  when: "try_login != 'Permission denied, please try again.'"

- name: Set new password for user {{ user.name }}
  user: 
    name: "{{ user.name }}"
    password: "{{ user.password }}"
  when: "try_login != 'Permission denied, please try again.'"