---
- name: "Update all packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install additional packages"
  apt:
    name: 
      - libxml2-dev
      - libxslt1-dev
    state: present

- name: "Set Hostname"
  hostname:
    name: "{{ hostname }}"
    
- name: "Set Hostname in hosts"
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1       raspberrypi'
    line: '127.0.0.1       {{ hostname }}'

- name: "Set Timezone to EST"
  timezone:
    name: America/New_York

- name: "Ensure utility present"
  package:
    name: sshpass
    state: present

- name: "Check for default password"
  command: sshpass -p raspberry ssh {{ user.name }}@localhost -o NoHostAuthenticationForLocalhost=yes "echo {{ ssh.login_success }}"
  register: try_login
  changed_when: "try_login.stdout == ssh['login_success']"
  failed_when: False

- name: "Set new password for user {{ user.name }}"
  user: 
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    state: present
  when: "try_login.stdout != ssh['login_success']"
