---
- name: Install qBittorrent
  package:
    name: qbittorrent-nox
    state: latest

- name: Add qBittorrent client user
  user:
    name: qbtuser
    group: null
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    comment: "qBittorrent client user"

- name: Copy qBittorrent service configuration file
  copy:
    src: "{{ qbit.service.src }}"
    dest: "{{ qbit.service.dest }}"
    owner: "root"
    group: "root"
    mode: 0644

- name: Activate qBittorrent service
  systemd:
    name: qbittorrent
    state: started
    daemon_reload: yes
    enabled: yes
