---
- name: Add Mopidy archive's GPG key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Add Mopidy APT repo to package sources
  get_url:
    url: https://apt.mopidy.com/stretch.list
    dest: /etc/apt/sources.list.d/mopidy.list

- name: Add Mopidy user
  user:
    name: mopidy
    group: null
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    comment: "Mopidy user"
    state: present

- name: Install Mopidy
  package:
    name: mopidy
    state: latest

- name: Create Mopidy configuration directory if it doesn't exist
  file:
    path: "{{ mopidy.conf.dest }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
    mode: 0644

- name: Copy Mopidy configuration file
  copy:
    src: "{{ mopidy.conf.src }}"
    dest: "{{ mopidy.conf.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: present
    mode: 0664
  register: copy_result

- name: Activate Mopidy service
  systemd:
    name: mopidy
    state: started
    daemon_reload: yes
    enabled: yes
