---
- name: Add Mopidy archive's GPG key
  command: wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -

- name: Add Mopidy APT repo to package sources
  command: sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/stretch.list

- name: Add Mopidy user
  user:
    name: mopidy
    group: null
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    comment: "Mopidy user"

- name: Install Mopidy
  package:
    name: mopidy
    state: latest

- name: Copy Mopidy configuration file
  copy:
    src: "{{ mopidy.conf.src }}"
    dest: "{{ mopidy.conf.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664

- name: Activate Mopidy service
  systemmd:
    enabled: {{ qbit.service.boot }}
    state: started
    name: mopidy
