---
- name: "Add Mopidy archive's GPG key"
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: "Add Mopidy APT repo to package sources"
  get_url:
    url: https://apt.mopidy.com/stretch.list
    dest: /etc/apt/sources.list.d/mopidy.list

- name: "Add user {{ mopidy.user.name }}"
  user:
    name: "{{ mopidy.user.name }}"
    group: null
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    comment: "Mopidy user"
    state: present

- name: "Install Mopidy"
  package:
    name: mopidy
    state: latest

# - name: "Create Mopidy configuration directory"
#   file:
#     path: "{{ mopidy.conf.dir }}"
#     state: directory
#     group: "{{ user.name }}"
#     owner: "{{ user.name }}"
#     mode: 0755

- name: "Copy Mopidy configuration file"
  copy:
    src: "{{ mopidy.conf.src }}"
    dest: "{{ mopidy.conf.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644
  register: copy_result
  changed_when: copy_result.changed
  failed_when: copy_result.failed
  ignore_errors: true

- name: "State of {{ mopidy.conf.dest }}"
  debug: 
    var: copy_result.state
    verbosity: "0"

- name: "Install Mopidy extensions"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - Mopidy-AudioAddict
    - Mopidy-GMusic
    - Mopidy-Local-SQLite
    - Mopidy-Moped
    - Mopidy-Podcast-iTunes
    - Mopidy-TuneIn
    - Mopidy-YouTube
  ignore_errors: true

- name: "Activate service {{ mopidy.service.name }}"
  systemd:
    name: "{{ mopidy.service.name }}"
    state: started
    daemon_reload: yes
    enabled: yes
  register: service_status
  changed_when: service_status.changed
  failed_when: service_status.status.ActiveState != "active"
  ignore_errors: true
  
- name: "State of service {{ mopidy.service.name }}"
  debug: 
    var: service_status.status.ActiveState
    verbosity: "0"
