---
- name: Add Mopidy archive's GPG key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg

- name: Add Mopidy APT repo to package sources
  command: sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/stretch.list

- name: Add Mopidy user
  user:
    name: mopidy
    group: null
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    comment: "Mopidy user"

- name: Install Mopidy
  package:
    name: mopidy
    state: latest

# Create Mopidy configuration file directory if it doesn't exist
- file:
    path: "{{ mopidy.conf.dest }}"
    state: directory
    mode: 0755

- name: Copy Mopidy configuration file
  copy:
    src: "{{ mopidy.conf.src }}"
    dest: "{{ mopidy.conf.dest }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664

- name: Activate Mopidy service
  systemd:
    enabled: yes
    state: started
    name: mopidy
